services:
  - type: web
    name: tetra-studio
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: DATA_FILE
        value: /tmp/data.json
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false